### ISSUE TITLE
Logo? 

### ISSUE THREAD

**Issue by trallard** [pyladies-nwuk/organisational#3]
Selina from Pyladies Chicago offered to help with the logo design

I image it would be some sort of a spin-off of the main PyLadies logo as most chapters do.
We need to make sure this captures the essence of the north of the UK. Thoughts?
![bitmoji](https://render.bitstrips.com/v2/cpanel/9d438724-a1e5-44b9-9172-377503bbffe6-65cddf2e-b04a-45ce-968f-9d23af39bf1e-v1.png?transparent=1&palette=1&width=246)

**Comment by katkoler** [comment]
Finished with logo design, it's in digital_assets. Currently we have it available in 4 different colours and 4 variations. 
![pyladies-logos](https://user-images.githubusercontent.com/17513720/41592066-5db4e5c4-73b3-11e8-8559-27b518be8b47.png)
Let me know if you want any changes.

**Comment by trallard** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/f70171d9-4f76-4409-b78f-8ed9b0076e12-4cf019d0-b710-4030-b809-40e959fb7998-v1.png?transparent=1&palette=1&width=246)


Thanks, the issue is closed for now
